task: errnews_et_instr
dataset_path: TalTechNLP/ERRnews
dataset_name: null
output_type: generate_until
generation_kwargs:
  until:
    - "\n\n"
  do_sample: false
  temperature: 0.0
training_split: null
validation_split: null
test_split: test
fewshot_split: null
doc_to_text: "{{transcript}}"
doc_to_target: summary
num_fewshot: 5
should_decontaminate: false
doc_to_decontamination_query: sentence
metric_list:
  - metric: !function utils.rouge1
    higher_is_better: true
    aggregation: !function utils.rouge1_agg
  - metric: !function utils.rouge2
    higher_is_better: true
    aggregation: !function utils.rouge2_agg
  - metric: !function utils.rougeL
    higher_is_better: true
    aggregation: !function utils.rougeL_agg    
  - metric: !function utils.average_len
    higher_is_better: false
    aggregation: !function utils.average_len_agg
metadata:
  version: 1.0
